---
apiVersion: v1
data:
{{- with .Values.envs }}
  {{- toYaml . | nindent 2 }}
{{- end }}
kind: ConfigMap
metadata:
  name: {{ include "core-microservice.fullname" . }}-configmap
  labels:
    {{- include "core-microservice.labels" . | nindent 4 }}