{{- if .Values.secrets }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "core-microservice.fullname" . }}-secretproviderclass
spec:
  provider: "azure"
  secretObjects:
  {{- range .Values.secrets }}
  - secretName: {{ lower .name }}
    type: Opaque
    data:
    - objectName: "{{ .name }}"
      key: "{{ .name }}"
  {{- end }}
  parameters:
    usePodIdentity: "false"
    clientID: "{{ .Values.secretproviderclass.clientID }}"  # Add other parameters as needed
    keyvaultName: "{{ .Values.secretproviderclass.keyvaultName }}"
    tenantId: "{{ .Values.secretproviderclass.tenantId }}"
    objects: |
      array:
      {{- range .Values.secrets }}
        - |-
          objectName: "{{ .name }}"
          objectType: secret
          objectVersion: ""
      {{- end }}
{{- end }}      